### PR TITLE
Life improvements

### PR DESCRIPTION
**Pull request by DotWith**
I'm not sure if this is buggy, but haven't run into any problems.

## StateCallback was removed due to...
- LoadingState Is something only fnf supports
- LoadingState is for when loading a week/shared folder
- People can add it to the finishCallback

## Major Changes
- removed stateCallback
- added readyCallback
- When trying to play videos during music will pause them. And resume after video is done playing.
- MP4Sprite has been added to clean up MP4Handler
- Fixed errors shown with VlcBitmap and LibVLC
- Made readme have examples on how to use in FNF

### CODE REVIEW

**Comment by DotWith** [comment]
I forgor to add enter to skip

**Comment by DotWith** [comment]
Ok, the video takes a little bit to load and once it does then the update function is called

**Comment by DotWith** [comment]
Don't accept I found a crash

**Comment by CryBitDev** [comment]
Uhh, so enter to skip is already added and made :trollface:.

**Comment by CryBitDev** [comment]
Dunno what are you tryna do but ok

**Comment by DotWith** [comment]
> Dunno what are you tryna do but ok

I was trying to make it more accessible to other games besides FnF

**Comment by DotWith** [comment]
Ok, no issues have been found with this. The only problem is the video player it's self and that no caching.

**Comment by Jrgamer4u** [comment]
is it just me or does the music play in the background when a video is playing

**Comment by polybiusproxy** [comment]
forgot to merge, there we go!

**Comment by polybiusproxy** [comment]
> is it just me or does the music play in the background when a video is playing

i thought i made a "FlxG.sound.music.stop()" is music is detected playing ;/
anyways it can be stopped manually before playing

**Pull request merged**
