### PR TITLE
2nd haxelib pull request (OLD)

### PR DESCRIPTION
**Pull request by Jrgamer4u**
something to do w/ #61 & #78

NOTE: the double digits (nearly triple) on the commits is when the project was more personal.
I am unable to make an second fork, with less commits.

### CODE REVIEW

**Comment by polybiusproxy** [comment]
holy thats a lot of commits

**Comment by MrClogsworthYT** [comment]
> holy thats a lot of commits

ikr

**Comment by Jrgamer4u** [comment]
""

**Comment by polybiusproxy** [comment]
> i is sdumb so here thhne the reason the exe file does not get built
> 
> ```
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: static class LibVLC * __cdecl LibVLC::create(void)" (?create@LibVLC@@SAPEAV1@XZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objonAddedToStage(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objonAddedToStage@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::play(void)" (?play@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objplay(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objplay@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::play(char const *)" (?play@LibVLC@@QEAAXPEBD@Z) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objplay(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objplay@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::stop(void)" (?stop@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objdispose(class hx::Object *)" (?__VlcBitmap_objdispose@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::pause(void)" (?pause@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objpause(class hx::Object *)" (?__VlcBitmap_objpause@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::resume(void)" (?resume@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objresume(class hx::Object *)" (?__VlcBitmap_objresume@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: __int64 __cdecl LibVLC::getLength(void)" (?getLength@LibVLC@@QEAA_JXZ) referenced in function "public: void __cdecl hxcodec::vlc::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@vlc@hxcodec@@QEAAXXZ)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: __int64 __cdecl LibVLC::getDuration(void)" (?getDuration@LibVLC@@QEAA_JXZ) referenced in function "public: void __cdecl hxcodec::vlc::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@vlc@hxcodec@@QEAAXXZ)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: int __cdecl LibVLC::getWidth(void)" (?getWidth@LibVLC@@QEAAHXZ) referenced in function "public: void __cdecl hxcodec::vlc::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@vlc@hxcodec@@QEAAXXZ)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: int __cdecl LibVLC::getHeight(void)" (?getHeight@LibVLC@@QEAAHXZ) referenced in function "public: void __cdecl hxcodec::vlc::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@vlc@hxcodec@@QEAAXXZ)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: unsigned char * __cdecl LibVLC::getPixelData(void)" (?getPixelData@LibVLC@@QEAAPEAEXZ) referenced in function "public: void __cdecl hxcodec::vlc::VlcBitmap_obj::render(void)" (?render@VlcBitmap_obj@vlc@hxcodec@@QEAAXXZ)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::setVolume(float)" (?setVolume@LibVLC@@QEAAXM@Z) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objsetVolume(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objsetVolume@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: float __cdecl LibVLC::getVolume(void)" (?getVolume@LibVLC@@QEAAMXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objgetVolume(class hx::Object *)" (?__VlcBitmap_objgetVolume@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: __int64 __cdecl LibVLC::getTime(void)" (?getTime@LibVLC@@QEAA_JXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objgetTime(class hx::Object *)" (?__VlcBitmap_objgetTime@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::setPosition(float)" (?setPosition@LibVLC@@QEAAXM@Z) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objseek(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objseek@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::setRepeat(int)" (?setRepeat@LibVLC@@QEAAXH@Z) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objplay(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objplay@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
> 97c1d656_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: float __cdecl LibVLC::getFPS(void)" (?getFPS@LibVLC@@QEAAMXZ) referenced in function "class Dynamic __cdecl hxcodec::vlc::__VlcBitmap_objgetFPS(class hx::Object *)" (?__VlcBitmap_objgetFPS@vlc@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
> ```

that error is caused by the linker, not sure how to fix it

**Comment by Jrgamer4u** [comment]
shit

**Comment by Jrgamer4u** [comment]
i think the reformatting was the problem, idk why but I think it works now.

**Comment by Jrgamer4u** [comment]
replaced by #80

**Pull request closed without merging**
