### PR TITLE
Fixes Loading Errors, and Forces Scaling with Window

### PR DESCRIPTION
**Pull request by deandimarzo**
Fixes error where it sometimes wouldn't load background assets after cutscene plays. Also gets the window size on loading, and scales cutscene to fit window.

### CODE REVIEW

**Comment by BL0KYBL0K** [comment]
THANK YOU

**Comment by BL0KYBL0K** [comment]
It Does nothing
you did not fix it

**Comment by deandimarzo** [comment]
> It Does nothing
> you did not fix it

You're still having the same issue?

**Comment by BL0KYBL0K** [comment]
> > It Does nothing
> > you did not fix it
> 
> You're still having the same issue?

yep im still haveing the same issue

**Comment by deandimarzo** [comment]
> > > It Does nothing
> > > you did not fix it
> > 
> > 
> > You're still having the same issue?
> 
> yep im still haveing the same issue

Can you share your github repository so I can take a look?

**Comment by polybiusproxy** [comment]
good job!
i'll merge after making some changes

**Comment by polybiusproxy** [comment]
thanks for your work!

**Comment by deandimarzo** [comment]
> thanks for your work!

Happy to help. Thanks for creating this awesome extension in the first place, couldn't have made my mod without it 😊

**Pull request merged**
