### PR TITLE
make this a haxelib

### LINKED ISSUE #61: Make this a haxelib
I think this should be a haxelib, to make it easier to install into a flixel project.

### PR DESCRIPTION
**Pull request by MrClogsworthYT**
resolves #61 
dont ask why i saw this in the projects tab
also the rest is required to be done by you so read [this](https://lib.haxe.org/documentation/creating-a-haxelib-package/)

### CODE REVIEW

**Comment by DotWith** [comment]
I was doing this >:(

**Comment by DotWith** [comment]
Yours wouldn't work as well becuase you forgor some crap

**Comment by DotWith** [comment]
@MrClogsworthYT This wouldn't work.

**Comment by MrClogsworthYT** [comment]
> @MrClogsworthYT This wouldn't work.

shit

**Comment by MrClogsworthYT** [comment]
> @MrClogsworthYT This wouldn't work.

fixed i think

**Comment by DotWith** [comment]
> > @MrClogsworthYT This wouldn't work.
> 
> fixed i think

You don't understand.

**Comment by DotWith** [comment]
Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?

**Comment by MrClogsworthYT** [comment]
> Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?

funk

**Comment by MrClogsworthYT** [comment]
> Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?

wait can't you make a pr in my pr

**Comment by DotWith** [comment]
> > Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?
> 
> wait can't you make a pr in my pr

I was already making this repo a haxelib. I was studding for some weeks.

**Comment by polybiusproxy** [comment]
omg big brain fight

**Comment by MrClogsworthYT** [comment]
> omg big brain fight

sus

**Comment by MrClogsworthYT** [comment]
> Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?

also flixel uses `import flixel.FlxG`

**Comment by DotWith** [comment]
> > Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?
> 
> also flixel uses `import flixel.FlxG`

no sshit. I said to allow lime and openfl support. Theres already flixel support. 😢 😢 😢

**Comment by MrClogsworthYT** [comment]
> > > Ok, you cannot just add a `haxelib.json` and expect everything to work. You need to redirect the buildXml and prevent from people including cpp from the vlc folder. Plus not to forget the import would be very terrible having to do `import source.MP4Handler`. Not to forget not all the contributors were added and the versioning being incorrect as it's supposed to follow [semantic versioning](https://semver.org/). How are you going to go around `openfl, lime, and flixel` for other project types?
> > 
> > 
> > also flixel uses `import flixel.FlxG`
> 
> no sshit. I said to allow lime and openfl support. Theres already flixel support. 😢 😢 😢

I dunno what ur talking about

**Comment by Jrgamer4u** [comment]
i was made a fork a while ago going in a similar idea of haxelibing but...
1. it brokey (something to do w/ libvlc idk)

2. i dumb

5. i children

4. i deleted some comments a while ago for some reason

- no lime and openfl support or whatever dot wither minecraft is saying

5. idk how to git the hub

[here the fork ig](https://github.com/Jrgamer4u/Friday-Night-Funkin-Mp4-Video-Support)

**Pull request closed without merging**
